<h2>Les marchés où me trouver :</h2>

<?php
$daysData = array(
    'lundi' => array('id' => 1),
    'mardi' => array('id' => 2),
    'mercredi' => array('id' => 3),
    'jeudi' => array('id' => 4),
    'vendredi' => array('id' => 5),
    'samedi' => array('id' => 6),
    'dimanche' => array('id' => 7)
);

foreach ($dates as $date) {
    switch ($date['id']) {
        case 1:
            $daysData['lundi'] = $date;
            break;
        case 2:
            $daysData['mardi'] = $date;
            break;
        case 3:
            $daysData['mercredi'] = $date;
            break;
        case 4:
            $daysData['jeudi'] = $date;
            break;
        case 5:
            $daysData['vendredi'] = $date;
            break;
        case 6:
            $daysData['samedi'] = $date;
            break;
        case 7:
            $daysData['dimanche'] = $date;
            break;
        case 8:
            $semaineData = $date;
            break;
    }
}
?>

<?php if (isset($semaineData)) : ?>
    <h3 data-field="semaine" data-day="<?= $semaineData['id']; ?>">Semaine du : <span id="spanWeek" class="editable"> <?= $semaineData['time']; ?></span></h3>
<?php endif; ?>

<table>
    <tr>
        <th></th>
        <th>heure</th>
        <th>ville</th>
        <th>lieu</th>
    </tr>
    <?php foreach ($daysData as $day => $data) : ?>
        <tr data-day="<?= $data['id']; ?>">
            <td><?= $day; ?></td>
            <td class="editable" data-field="time"><?= $data['time']; ?></td>
            <td class="editable" data-field="city"><?= $data['city']; ?></td>
            <td class="editable" data-field="place"><?= $data['place']; ?></td>
        </tr>
    <?php endforeach; ?>
</table>
<?php if (isset($_SESSION['user']) && ($_SESSION['user']['role'] == 1)) : ?>
    <button type="button" class="btn" id="saveBtn">Enregistrer</button>
<?php endif; ?>