<!-- <h2>Me contacter</h2> -->

<section class="contact">
    <?php include('dashboard.phtml'); ?>
</section>

<section class="contact">
    <div class="map">
        <div>
            <h3>les pâtes du chat</h3>
            <name-contact>MARTIN Arnaud</name-contact>
            <address>470 le Galley</br>73470 MARCIEUX</address>
            <a href="tel:+33620063662">06 20 06 36 62</a>
        </div>
        <div id="spinner"></div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11163.533420287522!2d5.76272!3d45.612988!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478b0f62c02cb8e3%3A0x1797d61db86d197c!2sLes%20p%C3%A2tes%20du%20chat!5e0!3m2!1sfr!2sfr!4v1682273961828!5m2!1sfr!2sfr" loading="lazy" allowfullscreen="" referrerpolicy="no-referrer-when-downgrade" id="lazy"></iframe>
    </div>
</section>

<section class="contact">
    <?php include('mail.phtml'); ?>
</section>