<section class="content">
    <h1>nous contacter</h1>

    <section class="contact">
        <h2>les marchés où me trouver :</h2>
        <h3>semaine du 17 au 23 avril :</h3>
        <table>
            <tr>
                <th></th>
                <th>heure</th>
                <th>ville</th>
                <th>emplacement</th>
            </tr>
            <tr>
                <td>lundi</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>mardi</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>mercredi</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>jeudi</td>
                <td>16h30 - 19h30</td>
                <td>Domessin </td>
                <td>à la ferme « A travers champs »</td>
            </tr>
            <tr>
                <td>vendredi</td>
                <td>16h - 19h30</td>
                <td>Nances</td>
                <td>parking à droite de la sortie d’autoroute avec pleins de produits locaux</td>
            </tr>
            <tr>
                <td>samedi</td>
                <td>8h30 - 12h</td>
                <td>Avressieux</td>
                <td>à la ferme « Des champs gourmands »</td>
            </tr>
            <tr>
                <td>dimanche</td>
                <td>8h-12h</td>
                <td>Novalaise</td>
                <td>-</td>
            </tr>
        </table>
    </section>

    <section class="contact">
        <h2>coordonnées</h2>
        <div class="map">
            <div>
                <h3>les pâtes du chat</h3>
                <address>470 le Galley</br>73470 MARCIEUX</address>
                <a href="tel:+33620063662">06 20 06 36 62</a>
            </div>
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11163.533420287522!2d5.76272!3d45.612988!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x478b0f62c02cb8e3%3A0x1797d61db86d197c!2sLes%20p%C3%A2tes%20du%20chat!5e0!3m2!1sfr!2sfr!4v1682273961828!5m2!1sfr!2sfr" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </section>

    <section class="contact">
        <h2>une question ? contactez-moi !</h2>
        <form action="index.php?route=sendContactMail" method="post">
            <div>
                <label for="name-contact">nom</label>
                <input type="text" name="name" id="name-contact">
            </div>
            <div>
                <label for="email-contact">email</label>
                <input type="email" name="email" id="email-contact">
            </div>
            <div>
                <label for="phone-contact">téléphone</label>
                <input type="tel" name="phone" id="phone-contact">
            </div>
            <div>
                <label for="message-contact">message</label>
                <textarea name="message" id="message-contact" cols="30" rows="10"></textarea>
            </div>
            <button class="btn" type="submit">Envoyer</button>
        </form>
    </section>
</section>