<section class="ML">

    <h1>MENTIONS LÉGALES</h1>

    <h2>ÉDITEUR</h2>
    <p>Le site Les-pates-du-chat.fr est édité par MARTIN Arnaud, entreprise individuelle immatriculée au RCS de Chambéry sous le numéro xxx xxx xxx xxx.</p>

    <h3>Siège social :</h3>
    <ul>
        <li>Les Pâtes du Chat</li>
        <li>470, le Gallay</li>
        <li>73470 MARCIEUX</li>
        <li>Numéro de TVA : FRxxxxxxxxxxx</li>
        <li>Téléphone : 07.xx.xx.xx.xx</li>
        <li>E-mail : lespatesduchat@gmail.com</li>
    </ul>

    <h2>HÉBERGEUR</h2>
    <h3>OVH</h3>
    <ul>
        <li>RCS Lille Métropole 424 761 419 00045</li>
        <li>Code APE 2620Z</li>
        <li>N° TVA : FR 22 424 761 419</li>
        <li>Siège social : 2 rue Kellermann - 59100 Roubaix - France</li>
        <li>Téléphone :1007</li>
    </ul>

    <h2>PROPRIÉTÉ INTELLECTUELLE</h2>
    <p>
        L'ensemble du site, y compris sa structure et son contenu (textes, tableaux, graphiques, images, photographies, vidéos, sons, bases de données, applications et logiciels), est protégé par le droit d'auteur et de propriété intellectuelle de l'éditeur ou de ses fournisseurs et prestataires.
    </p>

    <h2>DONNÉES PERSONNELLES</h2>
    <p>
        Ce site ne collecte aucune donnée sur les utilisateur.
    </p>

    <h2>COOKIES</h2>
    <p>
        L'éditeur du site utilise des cookies et autres traceurs ayant pour finalité exclusive de permettre ou faciliter une communication par voie électronique ou strictement nécessaires au bon fonctionnement du site.
        <br>
        Vous pouvez modifier les paramètres de votre navigateur pour bloquer ou supprimer les cookies. Le blocage des cookies peut altérer le fonctionnement du site. A tout moment vous avez la possibilité de modifier votre choix en ce qui concernent l'utilisation des cookies.
    </p>
</section>