<div class="menu-tabs">

    <input type="radio" class="hidden" id="tab1" name="tab-control">
    <input type="radio" class="hidden" id="tab2" name="tab-control" checked>
    <input type="radio" class="hidden" id="tab3" name="tab-control">
    <input type="radio" class="hidden" id="tab4" name="tab-control">

    <ul>
        <li tabindex="0"><label for="tab1" role="button"><span>news</span></label></li>
        <li tabindex="0"><label for="tab2" role="button"><span>boutique</span></label></li>
        <li tabindex="0"><label for="tab3" role="button"><span>recettes</span></label></li>
        <li tabindex="0"><label for="tab4" role="button"><span>contact</span></label></li>
    </ul>

    <div class="contenu-tabs">

        <!--------------- news --------------->
        <section class="section-tab">
            <h2>news</h2>
            <!-- display -->
            <h3>Toutes les actus</h3>
            <ul>
                <li>pagination</li>
                <li>confirm avant suppression</li>
                <li>truc over pour indiquer ce que fait le bouton</li>
                <li>rester sur le bon onglet</li>
            </ul>
            <table class="dashboard-table">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>titre</th>
                        <th>date de création</th>
                        <th colspan="3">actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($news as $actu) : ?>
                        <tr>
                            <td><?= $actu["id"] ?></td>
                            <td><?= $actu["title"] ?></td>
                            <td><?= $actu["created_at"] ?></td>
                            <td><a href="index.php?route=newsDetail&id=<?= $actu['id'] ?>">
                                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                </a></td>
                            <td><a href="index.php?route=displayUpdateNewsForm&id=<?= $actu['id'] ?>"><i class="fa-solid fa-pen-to-square"></i></a></td>
                            <td><a href="index.php?route=deleteNews&id=<?= $actu['id'] ?>"><i class="fa-solid fa-trash-can"></i></a></td>
                            <!-- onclick="confirmDelete()" -->
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <hr>

            <div class="buttons">
                <a href="index.php?route=displayCreateNewsForm" class="btn">créer une nouvelle actu</a>
            </div>

        </section>

        <!--------------- shop --------------->
        <section class="section-tab">
            <h2>boutique</h2>

            <!-- produits -->
            <h3>Tous les produits</h3>

            <ul>
                <li>pagination</li>
                <li>confirm avant suppression</li>
                <li>truc over pour indiquer ce que fait le bouton</li>
                <li>activer/masquer un produit</li>
            </ul>

            <table class="dashboard-table">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>produit</th>
                        <th>categorie</th>
                        <th>prix</th>
                        <th>en ligne</th>
                        <th colspan="2">actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($products as $product) : ?>
                        <tr>
                            <td><?= $product["id"] ?></td>
                            <td><?= $product["name"] ?></td>
                            <td><?= $product["cat_id"] ?></td>
                            <td><?= $product["price"] ?>€</td>
                            <td>
                                <!-- ajax -->
                                <form action="">
                                    <label class="switch">
                                        <input type="checkbox" <?php if ($product['active']) :
                                                                    echo 'checked';
                                                                endif; ?> />
                                        <span></span>
                                    </label>
                                </form>
                            </td>
                            <td><a href="index.php?route=shopDetail&id=<?= $product['id'] ?>" data-text="Voir le produit" class="aide left">
                                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                </a></td>
                            <td><a href="" data-text="Modifier le produit" class="aide left">
                                    <i class="fa-solid fa-pen-to-square"></i>
                                </a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <hr>

            <!-- category -->
            <h3>Toutes les catégories</h3>
            <ul>
                <li>pagination</li>
                <li>confirm avant suppression</li>
                <li>truc over pour indiquer ce que fait le bouton</li>
            </ul>
            <table class="dashboard-table">
                <thead>
                    <tr>
                        <th>id</th>
                        <th>categorie</th>
                        <th>nombre de produits</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($categories as $category) : ?>
                        <tr>
                            <td><?= $category["id"] ?></td>
                            <td><?= $category["name"] ?></td>
                            <td>
                                </ /?=$product["cat_id"] ?>
                            </td>
                            <td><a href=""><i class="fa-solid fa-pen-to-square"></i></a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            <hr>

            <div class="buttons">
                <a href="index.php?route=displayCreateProdForm" class="btn">créer un produit</a>
                <a href="index.php?route=displayCreateCatForm" class="btn">créer une catégorie</a>
            </div>
        </section>

        <!--------------- recipes --------------->

        <section class="section-tab">
            <h2>recettes</h2>
            <form action="index.php?route=submitRecipeForm" method="post">
                <div>
                    <label for="name">nom</label>
                    <input type="text" name="name" id="name" required>
                </div>
                <div>
                    <label for="product_id">inrédient principal</label>
                    <select name="product_id" id="product_id">
                        <option value="">---</option>
                        <?php foreach ($products as $product) : ?>
                            <option value="<?= $product['id'] ?>"><?= $product['name'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div>
                    <label for="difficulty">difficulté</label>
                    <input type="range" name="difficulty" id="difficulty" min="1" max="5">
                </div>
                <div>
                    <label for="time">temps</label>
                    <input type="time" name="time" id="time">
                </div>
                <div>
                    <label for="recipe">recette</label>
                    <textarea name="recipe" id="recipe" cols="30" rows="10" required></textarea>
                </div>
                <div>
                    <label for="thermostat">thermostat</label>
                    <input type="number" name="thermostat" id="thermostat">
                </div>
                <div>
                    <label for="portions">nombre de personnes</label>
                    <input type="number" name="portions" id="portions">
                </div>
                <div>
                    <label for="img">image</label>
                    <input type="file" name="img" id="img">
                </div>
                <button type="submit" class="btn" value="">envoyer</button>
            </form>
        </section>

        <section class="section-tab">
            <h2>contact</h2>

        </section>

    </div>

</div>