<section>
    <h2>news</h2>
    ckeditor
</section>

<section class="dashboard">
    <h2>boutique</h2>
    

    <form action="index.php?route=submitCatForm" method="post">
        <h3>Créer une nouvelle catégorie</h3>
        <div>
            <label for="name">nom</label>
            <input type="text" name="name" id="name" required>
        </div>
        <div>
            <label for="descript">decription</label>
            <textarea name="descript" id="decript" cols="30" rows="10"></textarea>
        </div>
        <button type="submit" class="btn" value="submit">envoyer</button>
    </form>

    <form action="index.php?route=submitProdForm" method="post">
        <h3>Créer un nouveau produit</h3>
        <div>
            <label for="name">nom</label>
            <input type="text" name="name" id="name" required>
        </div>
        <div>
            <label for="category">catégorie</label>
            <select name="category" id="category">
                <?php foreach ($categories as $category) : ?>
                    <option value="<?= $category['id'] ?>"><?= $category['name'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div>
            <label for="descript">decription</label>
            <textarea name="descript" id="descript" cols="30" rows="10"></textarea>
        </div>
        <div>
            <label for="price">prix</label>
            <input type="number" name="price" id="price" required>
        </div>
        <div>
            <label for="img">image</label>
            <input type="file" class="file" name="img" id="img">
        </div>
        <button type="submit" class="btn" value="submit">envoyer</button>
    </form>
</section>

<section>
    <h2>recettes</h2>
    <form action="" method="post">
        <div>
            <label for="">nom</label>
            <input type="text" name="" id="" required>
        </div>
        <div>
            <label for="">recette</label>
            <textarea name="" id="" cols="30" rows="10"></textarea>
        </div>
        <div>
            <label for="">image</label>
            <input type="file" name="" id="">
        </div>
        <button type="submit" class="btn" value="">envoyer</button>
    </form>
</section>

<section>
    <h2>contact</h2>

</section>