<?php if (isset($_SESSION['visitor']['flash_message']['success'])) : ?>
    <div class="success">
        <?= htmlspecialchars($_SESSION['visitor']['flash_message']['success']); ?>
    </div>
<?php endif; ?>

<?php if (isset($_SESSION['visitor']['flash_message']['error'])) : ?>
    <div class="error">
        <?php foreach ($errors as $error) : ?>
            <?= $error; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
