<?php if (isset($_SESSION['visitor']['flash_message']['success'])) : ?>
    <div class="success">
        <?= htmlspecialchars($_SESSION['visitor']['flash_message']['success']); ?>
    </div>
<?php endif; ?>

<?php if (isset($_SESSION['visitor']['flash_message']['error'])) : ?>
    <div class="error">
        <?php if (is_array($_SESSION['visitor']['flash_message']['error'])) : ?>
            <?php foreach ($_SESSION['visitor']['flash_message']['error'] as $error) : ?>
                <?= $error; ?>
            <?php endforeach; ?>
        <?php else : ?>
            <?= $_SESSION['visitor']['flash_message']['error']; ?>
        <?php endif; ?>
    </div>
<?php endif; ?>