<section class="home" id="home">
    <a href="index.php?route=home">
        <div id="title">
            <h1>Les Pâtes du Chat</h1>
            <h2>Artisan pastier de l’avant-pays Savoyard</h2>
        </div>
    </a>
    <article>
        <img src="./public/img/site/Logo-Arnaud.png" alt="Logo" id="logo">
        <table>
            <tr>
                <td><img src="./public/img/site/pateL.png" alt="une patte de petit chat-mignon"></td>
                <td>Des recettes qui varient au fil des saisons.</td>
                <td><img src="./public/img/site/pateR.png" alt="une autre trace de patte du petit chat-mignon"></td>
            </tr>
            <tr>
                <td><img src="./public/img/site/pateR.png" alt="encore une ici"></td>
                <td>Des produits bio et/ou issus de nos terres régionales.</td>
                <td><img src="./public/img/site/pateL.png" alt="ici aussi"></td>
            </tr>
            <tr>
                <td><img src="./public/img/site/pateL.png" alt="et puis là"></td>
                <td>Le respect de l'écologie et du bien-être animal.</td>
                <td><img src="./public/img/site/pateR.png" alt="et aussi ici"></td>
            </tr>
            <tr>
                <td><img src="./public/img/site/pateR.png" alt="là"></td>
                <td>Des saveurs uniques, qui font briller les yeux et ravissent les papilles !</td>
                <td><img src="./public/img/site/pateL.png" alt="et encore là"></td>
            </tr>
        </table>
    </article>

</section>
<section class="home scroll reveal" id="shop">
    <?php include('shop/home.phtml'); ?>
</section>
<section class="home scroll revealL" id="news">
    <?php include('news/home.phtml'); ?>
</section>
<section class="home scroll revealR" id="recipes">
    <?php include('recipes/home.phtml'); ?>
</section>
<section class="home scroll reveal" id="contact">
    <?php include('contact/home.phtml'); ?>
</section>