<section class="home" id="home">
    <h1>HELLO WORLD</h1>
    <article>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer ut ligula nec felis mollis iaculis at sed metus. Integer egestas ligula gravida volutpat aliquet. Proin lectus ligula, sagittis vulputate faucibus at, consectetur sit amet sem. Vestibulum condimentum pharetra ante, id faucibus diam. Fusce vitae nibh nec sapien blandit congue. Curabitur facilisis ipsum in lacus ornare, vel elementum lectus volutpat. Nunc eleifend fermentum felis. Donec faucibus ligula in egestas aliquet.
        </p>
        <p>
            Vivamus fermentum massa eu metus consectetur consectetur. Etiam nec est risus. Aliquam sed nisi vitae magna tristique tristique vitae vel augue. Maecenas semper felis arcu, non congue dolor mattis sit amet. Pellentesque nunc tellus, hendrerit eget diam vel, imperdiet rhoncus nunc. Nam lectus mi, facilisis sed gravida quis, interdum nec eros. Mauris pellentesque ante quis ante mollis, id bibendum purus tempus. Donec sed ex eu urna pellentesque mattis non vitae tortor. Proin ac tincidunt dolor. Aliquam tempus molestie eros, nec tincidunt lacus aliquet in. Proin tincidunt consequat metus, commodo tempor arcu fringilla nec.
        </p>
    </article>
</section>
<section class="home scroll reveal" id="news">
    <?php include('shop/home.phtml'); ?>
</section>
<section class="home scroll revealL" id="shop">
    <?php include('news/home.phtml'); ?>
</section>
<section class="home scroll revealR" id="recipes">
    <?php include('recipes/home.phtml'); ?>
</section>
<section class="home scroll reveal" id="contact">
    <?php include('contact/home.phtml'); ?>
</section>