<header class="home" id="home">
    <a href="index.php?route=home">
        <div id="title">
            <h1>Les Pâtes du Chat</h1>
            <h2>Artisan pastier de l’avant-pays Savoyard</h2>
        </div>
    </a>

    <div id="title-landscape">
        <div>
            <h1>Les Pâtes du Chat</h1>
            <h2>Artisan pastier de l’avant-pays Savoyard</h2>
        </div>
        <img src="./public/img/site/Logo-Arnaud.png" class="logo" alt="Logo">
    </div>

    <div class="petits-chats">
        <img src="./public/img/site/Logo-Arnaud.png" alt="Logo" class="logo" id="logo">
        <table>
            <tr>
                <td><img src="./public/img/site/pateL.png" alt="une patte de chat"></td>
                <td>Des recettes qui varient au fil des saisons.</td>
                <td><img src="./public/img/site/pateR.png" alt="une patte de chat"></td>
            </tr>
            <tr>
                <td><img src="./public/img/site/pateR.png" alt="une patte de chat"></td>
                <td><strong>Des produits bio</strong> et/ou issus de nos terres régionales.</td>
                <td><img src="./public/img/site/pateL.png" alt="une patte de chat"></td>
            </tr>
            <tr>
                <td><img src="./public/img/site/pateL.png" alt="une patte de chat"></td>
                <td>Le respect de <strong>l'écologie</strong> et du <strong>bien-être animal</strong>.</td>
                <td><img src="./public/img/site/pateR.png" alt="une patte de chat"></td>
            </tr>
            <tr>
                <td><img src="./public/img/site/pateR.png" alt="une patte de chat"></td>
                <td><strong>Des saveurs uniques</strong>, qui font briller les yeux et ravissent les papilles !</td>
                <td><img src="./public/img/site/pateL.png" alt="une patte de chat"></td>
            </tr>
        </table>
    </div>
</header>

<section class="home" id="shop">
    <?php include('shop/home.phtml'); ?>
</section>
<section class="home" id="contact">
    <?php include('contact/home.phtml'); ?>
</section>