<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Non repertorié -->
    <meta name="robots" content="noindex, nofollow">

    <title>Les Pâtes du Chat</title>
    <link rel="icon" href="./public/img/site/Favicon.png" type="image/x-icon">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <!--Font Awesome 6-->
    <script src="https://kit.fontawesome.com/267127ee95.js" crossorigin="anonymous"></script>
    <!-- Style -->
    <link rel="stylesheet" type="text/css" href="public/css/main.css">
</head>

<body>
    <header>
        <?php include_once('nav.phtml'); ?>
    </header>

    <main>
        <?php if (!isset($_SESSION['user'])) : ?>
            <aside class="modal-log" id="modal">
                <?php include_once('users/login.phtml'); ?>
                <?php include_once('users/register.phtml'); ?>
            </aside>
        <?php endif ?>

        <?php if (isset($_SESSION['visitor']['flash_message'])) : ?>
            <aside>
                <?php include_once('./views/flash_msg.phtml'); ?>
            </aside>
            <?php unset($_SESSION['visitor']['flash_message']); ?>
        <?php endif ?>

        <?php if (isset($template) && $template == "home.phtml") : ?>
            <section>
            <?php else : ?>
                <section class="container">
                <?php endif ?>
                <?php include $template; ?>
                </section>
    </main>

    <!-- Style -->
    <script type="module" src="public/js/style.js"></script>
</body>

</html>