<?php require_once('./index.php'); ?>
<nav>
    <ul class="pages">
        <li><a href="index.php?route=shop">Les pâtes fraîches</a></li>
        <li><a href="index.php?route=contactPage">Les marchés</a></li>
    </ul>

    <ul class="title" id="title">
        <a href="index.php?route=home">Les Pâtes du Chat</a>
    </ul>

    <ul class="account">
        <li><a href="index.php?route=contactMail">contact</a></li>

        <!-- accès gestion du site -->
        <?php if (isset($_SESSION['user']) && ($_SESSION['user']['role'] == 1)) : ?>
            <li><a href="index.php?route=admin">tableau de bord</a></li>
        <?php endif; ?>

        <!-- accès gestion du compte -->
        <?php if (isset($_SESSION['user']) && !empty($_SESSION['user'])) : ?>
            <li class="dropdown">
                <a class="dropdown-toggle" role="button" id="dropdown-toggle">
                    <?php if (isset($_SESSION['user']['name'])) : ?>
                        <?= htmlspecialchars($_SESSION['user']['name']); ?>
                    <?php else : ?>
                        <?= htmlspecialchars($_SESSION['user']['email']); ?>
                    <?php endif; ?>
                </a>
                <ul class="dropdown-menu" id="dropdown-menu">
                    <li><a href="index.php?route=myAccount">mon compte</a></li>
                    <li><a href="index.php?route=logout">déconnexion</a></li>
                </ul>
            </li>
        <?php else : ?>
            <li id="loggin">connexion</li>
        <?php endif; ?>
    </ul>
</nav>