<?php require_once('./index.php') ?>
<nav>
    <ul class="pages">
        <li><a href="index.php?route=home">accueil</a></li>
        <li><a href="index.php?route=news">news</a></li>
        <li><a href="index.php?route=shop">boutique</a></li>
        <li><a href="index.php?route=recipes">recettes</a></li>
        <li><a href="index.php?route=contact">contact</a></li>
        <?php if (isset($_SESSION['user']) && ($_SESSION['user']['role'] == 1)) : ?>
            <li><a href="index.php?route=admin">tableau de bord</a></li>
        <?php endif; ?>
    </ul>

    <ul class="account">
        <?php if (isset($_SESSION['user']) && !empty($_SESSION['user'])) : ?>
            <li class="dropdown">
                <a class="dropdown-toggle" role="button" id="dropdown-toggle">
                    <?php if (isset($_SESSION['user']['name'])) : ?>
                        <?= htmlspecialchars($_SESSION['user']['name']) ?>
                    <?php else : ?>
                        <?= htmlspecialchars($_SESSION['user']['email']) ?>
                    <?php endif; ?>
                </a>
                <ul class="dropdown-menu" id="dropdown-menu">
                    <li><a href=" index.php?route=myAccount">mon compte</a></li>
                    <li><a href="#">mon panier</a></li>
                    <li><a href="#">mes commandes</a></li>
                    <li><a href="index.php?route=logout">déconnexion</a></li>
                </ul>
            </li>
        <?php else : ?>
            <li id="loggin">connexion</li>
            <li id="register">nouveau compte</li>
        <?php endif; ?>
    </ul>
</nav>