<section class="content">
    <?php if (isset($category['id'])): ?>

        <h3>modifier une catégorie</h3>
        <form action="index.php?route=updateCatForm&id=<?= htmlspecialchars($category["id"]) ?>" method="post">
            <div>
                <label for="name">nom</label>
                <input type="text" name="name" id="name" required value="<?= htmlspecialchars($category["name"]) ?>">
            </div>
            <div>
                <label for="descript">decription</label>
                <textarea name="descript" id="decript" cols="30" rows="10"><?= htmlspecialchars($category["descript"]) ?></textarea>
            </div>

            <div class="buttons">
                <button type="submit" class="btn" value="submit">envoyer</button>
                <button href="index.php?route=admin" class="btn">annuler</button>
            </div>
        </form>

    <?php else: ?>

        <h3>créer une catégorie</h3>
        <form action="index.php?route=submitCatForm" method="post">
            <div>
                <label for="name">nom</label>
                <input type="text" name="name" id="name" required>
            </div>
            <div>
                <label for="descript">decription</label>
                <textarea name="descript" id="decript" cols="30" rows="10"></textarea>
            </div>

            <div class="buttons">
                <button type="submit" class="btn" value="submit">envoyer</button>
                <button href="index.php?route=admin" class="btn">annuler</button>
            </div>
        </form>

    <?php endif; ?>
</section>