<section class="content">
    <figure class="shop-detail">
        <?php if (!empty($product["img"])) : ?>
            <img src="public/img/produits/<?= $product['image']; ?>" alt="<?= $product['imgTitle']; ?>">
        <?php else : ?>
            <img src="public/img/site/logo-Arnaud.png" alt="Image non disponible">
        <?php endif; ?>
        <figcaption>
            <h1><?= htmlspecialchars($product["name"]); ?></h1>
            <p><?= htmlspecialchars($product["descript"]); ?></p>
            <p><?= htmlspecialchars($product["price"]); ?>€</p>
        </figcaption>
    </figure>
</section>