<h3>Ajouter une image</h3>
<form id="imgForm" method="post" enctype="multipart/form-data">
    <div>
        <label for="img">image</label>

        <?php if (isset($product['id'])) : ?>
            <input type="hidden" name="productId" id="productId" value=<?= $product['id']; ?>>
        <?php endif; ?>

        <img id="previewImage" src="#" alt="Image Preview" style="display: none;">
        <input type="file" class="file" name="img" id="img">

        <figure>
            <?php if (!empty($product["img"])) : ?>
                <img id="productImage" src="public/img/produits/<?= $product['image']; ?>" alt="<?= $product['imgTitle']; ?>">
                <figcaption>
                    <?= $product['imgTitle']; ?>
                </figcaption>
            <?php else : ?>
                <i class="fa-regular fa-image"></i>
                <figcaption>Aucune image</figcaption>
            <?php endif; ?>
        </figure>
    </div>

    <?php if (isset($product['id'])) : ?>
        <div id="imgBtn">
            <button type="submit" class="btn" value="submit" form="imgForm">envoyer</button>
            <button class="btn">supprimer</button>
        </div>
    <?php endif ?>

    <div id="imgMsg"></div>
</form>