<section class="content dashboard-form">
    <?php if (isset($product['id'])) : ?>

        <h2>modifier un produit</h2>
        <form action="index.php?route=updateProdForm&id=<?= htmlspecialchars($product['id']); ?>" method="post" enctype="multipart/form-data">
            <div>
                <label for="name">nom</label>
                <input type="text" name="name" id="name" required value="<?= htmlspecialchars($product["name"]); ?>">
            </div>
            <div>
                <label for="category">catégorie</label>
                <select name="category" id="category">
                    <option value="<?= htmlspecialchars($product['cat_id']); ?>"><?= htmlspecialchars($product['categoryProduct']); ?></option>
                    <?php foreach ($categories as $category) : ?>
                        <?php if($category['name'] != $product['categoryProduct']): ?>
                            <option value="<?= htmlspecialchars($category['id']); ?>"><?= htmlspecialchars($category['name']); ?></option>
                        <?php endif ?>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <label for="descript">decription</label>
                <textarea name="descript" id="descript" cols="30" rows="10"><?= htmlspecialchars($product["descript"]); ?></textarea>
            </div>
            <div>
                <label for="price">prix</label>
                <input type="number" min="1" step="any" name="price" id="price" required value="<?= $product["price"] ?>">
            </div>
            <div>
                <label for="img">image</label>
                <input type="file" class="file" name="img" id="img">
                <img src="public/img/produits/<?= $product['image']; ?>" alt="<?= $product['imgTitle']; ?>">
            </div>

            <div class="buttons">
                <button type="submit" class="btn" value="submit">envoyer</button>
                <a type="button" href="index.php?route=admin" class="btn">annuler</a>
            </div>
        </form>

    <?php else : ?>

        <h2>créer un produit</h2>
        <form action="index.php?route=submitProdForm" method="post" enctype="multipart/form-data">
            <div>
                <label for="name">nom</label>
                <input type="text" name="name" id="name" required>
            </div>
            <div>
                <label for="category">catégorie</label>
                <select name="category" id="category">
                    <?php foreach ($categories as $category) : ?>
                        <option value="<?= htmlspecialchars($category['id']); ?>"><?= htmlspecialchars($category['name']); ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <label for="descript">decription</label>
                <textarea name="descript" id="descript" cols="30" rows="10"></textarea>
            </div>
            <div>
                <label for="price">prix</label>
                <input type="number" min="1" step="any" name="price" name="price" id="price" required>
            </div>
            <div>
                <label for="img">image</label>
                <input type="file" class="file" name="img" id="img">
                <!-- afficher un apperçu -->
            </div>

            <div class="buttons">
                <button type="submit" class="btn" value="submit">envoyer</button>
                <a href="index.php?route=admin" class="btn">annuler</a>
            </div>
        </form>

    <?php endif; ?>
</section>