<section class="content dashboard-form">
    <?php if (isset($product['id'])) : ?>
        <!-- Formulaire pour modifier un produit -->
        <h2>Modifier un produit</h2>
        <?php $action = "index.php?route=updateProdForm&id=" . htmlspecialchars($product['id']); ?>
    <?php else : ?>
        <!-- Formulaire pour créer un nouveau produit -->
        <h2>Créer un produit</h2>
        <?php $action = "index.php?route=submitProdForm"; ?>
    <?php endif; ?>

    <form id="productForm" action="<?= $action ?>" method="post" enctype="multipart/form-data">
        <div id="nameInput">
            <label for="name">Nom *</label>
            <input type="text" name="name" id="name" placeholder="youpi" value="<?= isset($product["name"]) ? htmlspecialchars($product["name"]) : '' ?>">
        </div>

        <div id="categoryInput">
            <label for="category">Catégorie</label>
            <select name="category" id="category">
                <?php foreach ($categories as $category) : ?>
                    <?php $categoryId = htmlspecialchars($category['id']); ?>
                    <?php $categoryName = htmlspecialchars($category['name']); ?>
                    <option value="<?= $categoryId ?>" <?= isset($product['cat_id']) && $product['cat_id'] == $categoryId ? 'selected' : '' ?>><?= $categoryName ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div id="descriptInput">
            <label for="descript">Description</label>
            <textarea name="descript" id="descript" cols="30" rows="10"><?= isset($product["descript"]) ? htmlspecialchars($product["descript"]) : '' ?></textarea>
        </div>

        <div id="ingredientsInput">
            <label for="ingredients">Ingrédients</label>
            <textarea name="ingredients" id="ingredients" cols="30" rows="10">
                <?= isset($product["ingredients"]) ? htmlspecialchars($product["ingredients"]) : '' ?>
            </textarea>
        </div>

        <div id="priceInput">
            <label for="price">Prix *</label>
            <input type="number" min="1" step="any" name="price" id="price" value="<?= isset($product["price"]) ? $product["price"] : '' ?>">
        </div>

        <?php if (!isset($product['id'])) : ?>
            <input type="hidden" id="imgLoaded" name="imgLoaded" value="0">
        <?php endif; ?>
    </form>

    <div id="imgInput" class="imgForm">
        <?php include('imgForm.phtml'); ?>
    </div>

    <div class="buttons">
        <button type="submit" class="btn" value="submit" form="productForm">Envoyer</button>
        <a href="index.php?route=admin" class="btn">Annuler</a>
    </div>
</section>