<section class="shop-view">
    <h2>Tous les articles</h2>
    <?php foreach ($products as $product) : ?>
        <h3><?= $product["name"] ?></h3>
        <figure class="shop-tuile">
            <!-- <a href="{{route('shopping.show', $product->id)}}"> -->
            <!-- @if ($product->image)
                    <img src="/images/{{$product->img}}" alt="">
                    @else -->
            <img src="/public/img/Hades.jpg" alt="">
            <!-- @endif -->
            <figcaption>
                <h5><?= $product["name"] ?></h5>
                <p><?= $product["descript"] ?></p>
                <p><?= $product["price"] ?>€</p>
                <p class="btn">Voir plus</p>
            </figcaption>
            <!-- </a> -->
        </figure>
    <?php endforeach; ?>
</section>