<div class="log noScroll" id="log_window">
    <i class="fa-solid fa-x close-btn" id="close-log"></i>
    <h2>Connexion</h2>

    <form action="index.php?route=connect" method="post" id="login-form">
        <div class="champs">
            <label for="email_log">email</label>
            <input type="email" name="email" id="email_log" autocomplete="email">
            <div class="error" id="error_log_mail">
                <?php if (isset($errorLog)) : ?>
                    <span id="errorL"><?= htmlspecialchars($errorLog); ?></span>
                <?php endif; ?>
            </div>
        </div>
        <div class="champs password">
            <label for="pswd_log">mot de passe</label>
            <div>
                <input type="password" name="pswd" id="pswd_log" autocomplete="password">
                <i class="fa-solid fa-eye" id="login-show"></i>
                <i class="fa-regular fa-eye hidden" id="login-hide"></i>
            </div>
            <div class="error" id="error_log_pswd"></div>

            <a href="" class="btn" id="forgot">Mot de passe oublié ?</a>
        </div>

        <button type="submit" class="btn" id="validate-log">valider</button>
    </form>

    <div class="trans-btn">
        <p class="btn">Pas de compte ?</p>
        <a class="btn" id="register">Créer un compte</a>
    </div>
</div>