<div class="log" id="log_window">
    <i class="fa-solid fa-xmark croix-btn" id="close-log"></i>
    <h2>Connexion</h2>

    <form action="index.php?route=connect" method="post" id="login-form">
        <div class="champs">
            <label for="email_log">email</label>
            <input type="email" name="email" id="email_log">
            <div class="error" id="error_log_mail"></div>
        </div>
        <div class="champs password">
            <label for="pswd_log">mot de passe</label>
            <div>
                <input type="password" name="pswd" id="pswd_log">
                <i class="fa-solid fa-eye" id="login-show"></i>
                <i class="fa-regular fa-eye hidden" id="login-hide"></i>
            </div>
            <div class="error" id="error_log_pswd"></div>

            <a href="" class="btn" id="forgot">Mot de passe oublié ?</a>
        </div>

        <button type="submit" class="btn" id="validate-log">valider</button>
    </form>

    <div class="trans-btn">
        <p class="btn" id="ask-new">Pas de compte ?</p>
        <a class="btn" id="new-account">Créer un compte</a>
    </div>
</div>