<section class="userProfil">
    <h2>Mon compte</h2>

    <div class="profil">
        <section>
            <h2>Informations personnelles</h2>

            <form action="index.php?route=changeNameForm" method="post">
                <h3>Changer mon nom</h3>
                <div>
                    <input type="text" name="name" class="text-input" id="name" value="<?= htmlspecialchars($user['name']); ?>">
                    <input type="submit" class="btn" value="Valider">
                </div>
            </form>

            <!-- <form action="index.php?route=changeMailForm" method="post">
                <h3>Changer mon email de contact</h3>
                <div>
                    <input type="email" name="email" class="text-input" id="email" value="< ?= htmlspecialchars($user['email']); ?>">
                    <input type="submit" class="btn" value="Valider">
                </div>
            </form> -->

            <form action="" method="post" id="newsletter">
                <h3>S'abonner à la newsletter</h3>
                <div>
                    <input type="checkbox" name="newsletter" id="newsletterCheck" value="checked" checked>
                    <label for="newsletterCheck">Je souhaite recevoir toutes les informations du magasin</label>
                </div>
            </form>
        </section>


        <section>
            <h2>Gestion du compte</h2>
            <form action="" method="post">
                <!-- route=resetPswd -->
                <h3>Changer mon mot de passe</h3>
                <input type="submit" class="btn" value="Envoyer le lien par email">
            </form>

            <form action="index.php?route=desactivateUser" id="disable" method="post">
                <h3>Désactiver mon compte</h3>
                <p>Attention, vous ne pourrez plus accéder à votre compte si vous le désactivez.</p>
                <input type="submit" class="btn" value="Désactiver">
            </form>
        </section>
    </div>
</section>