<section class="userProfil">
    <h1>Mon compte</h1>

    <!-- <ul>
        <li>changer mot de passe</li>
        <li>envoyer mail de confirmation d'adresse</li>
        <li>récupérer mot de passe par email</li>
    </ul> -->

    <div class="profil">
        <section>
            <h2>Informations personnelles</h2>

            <form action="index.php?route=changeNameForm" method="post">
                <h3>Changer mon nom</h3>
                <div>
                    <label for="name">Nom</label>
                    <input type="text" name="name" id="name" value="<?= htmlspecialchars($user['name']); ?>">
                    <input type="submit" class="btn" value="Valider">
                </div>
            </form>

            <form action="index.php?route=changeMailForm" method="post">
                <h3>Changer mon email de contact</h3>
                <div>
                    <label for="email">email</label>
                    <input type="email" name="email" id="email" value="<?= htmlspecialchars($user['email']); ?>">
                    <input type="submit" class="btn" value="Valider">
                </div>
            </form>

            <form action="" method="post" id="newsletter">
                <h3>S'abonner à la newsletter</h3>
                <div>
                    <input type="checkbox" name="newsletter" id="newsletterCheck" value="checked" checked>
                    <label for="newsletterCheck">Je souhaite recevoir toutes les informations du magasin</label>
                </div>
            </form>
        </section>


        <section>
            <h2>Gestion du compte</h2>
            <form action="index.php?route=changePswdForm" method="post">
                <h3>Changer mon mot de passe</h3>
                <div>
                    <label for="pswd">mot de passe</label>
                    <input type="password" name="pswd" id="pswd">
                    <input type="submit" class="btn" value="Valider">
                </div>
            </form>

            <form action="index.php?route=desactivateUser" method="post">
                <h3>Désactiver mon compte</h3>
                <p>Attention, vous ne pourrez plus accéder à votre compte si vous le désactivez.</p>
                <div>
                    <label>Désactiver</label>
                    <input type="submit" class="btn" value="Supprimer">
                </div>
            </form>
        </section>
    </div>

    <!-- if compte désactivé, on pourra demader à supprimer le compte de la db -->

    <!-- <form action="index.php?route=deleteUser" method="post">
        <div>
            <label>Supprimer le compte</label>
        </div>
        <input type="submit" class="btn" value="Supprimer">
    </form> -->
</section>