<h1>Mon compte</h1>

<form action="index.php?route=changeNameForm" method="post">
    <div>
        <label for="name">Nom</label>
        <input type="text" name="name" id="name">
    </div>
    <input type="submit" class="btn" value="Valider">
</form>

<form action="index.php?route=changeMailForm" method="post">
    <div>
        <label for="email">email</label>
        <input type="email" name="email" id="email">
    </div>
    <input type="submit" class="btn" value="Valider">
</form>

<form action="index.php?route=changePswdForm" method="post">
    <div>
        <label for="pswd">mot de passe</label>
        <input type="password" name="pswd" id="pswd">
    </div>
    <input type="submit" class="btn" value="Valider">
</form>