<div class="log" id="register-window">
    <i class="fa-solid fa-xmark croix-btn" id="close-register"></i>
    <h2>Nouveau compte</h2>

    <form action="index.php?route=register" method="post" id="register-form">
        <div class="champs">
            <label for="email_new">email</label>
            <input type="email" name="email" id="email_new">
            <div class="error" id="error_new_mail"></div>
        </div>
        
        <div class="champs password">
            <label for="pswd_new">mot de passe</label>
            <div>
                <input type="password" name="pswd" id="pswd_new">
                <i class="fa-solid fa-eye" id="register-show"></i>
                <i class="fa-regular fa-eye none" id="register-hide"></i>
            </div>
            <div class="error" id="error_new_pswd"></div>
        </div>

        <div class="champs">
            <label for="pswd_confirm_new">confirmez votre mot de passe</label>
            <input type="password" name="pswd_confirm" id="pswd_confirm_new">
            <div class="error" id="error_new_verif"></div>
        </div>

        <button type="submit" class="btn" value="Valider" id="validate-register">valider</button>
    </form>

    <div class="flex">
        <p>Déjà un compte ?</p>
        <a class="btn" id="connexion">Connexion</a>
        <!-- un seul bouton -->
    </div>
</div>