<section class="userProfil resetPswd">
    <h2>Réinitialisation du mot de passe</h2>

    <!-- <div class="travaux">
        <p>En travaux</p>
    </div> -->

    <form action="index.php?route=resetPswdForm" method="post">
        <h3>Choisissez un nouveau mot de passe</h3>
        <div class="resetForm">
            <div class="champs">
                <label for="email_rst">email</label>
                <input type="email" id="email_rst" value="<?= htmlspecialchars($user['email']); ?>" disabled>
            </div>

            <div class="champs password">
                <label for="pswd_rst">nouveau mot de passe</label>
                <div>
                    <input type="password" name="pswd_rst" id="pswd_rst">
                    <i class="fa-solid fa-eye" id="rst-show"></i>
                    <i class="fa-regular fa-eye" id="rst-hide"></i>
                </div>
                <div class="error" id="error_rst"></div>
            </div>

            <div class="champs password">
                <label for="pswd_confirm_rst">confirmez votre mot de passe</label>
                <div>
                    <input type="password" name="pswd_confirm_rst" id="pswd_confirm_rst">
                    <i class="fa-solid fa-eye" id="confirm-rst-show"></i>
                    <i class="fa-regular fa-eye" id="confirm-rst-hide"></i>
                </div>
                <div class="error" id="error_rst_verif"></div>
            </div>
            <button type="submit" class="btn" value="Valider" id="validate-reset">valider</button>
        </div>
    </form>

    <div class="advertise">
        <h3>Conseils de sécurité :</h3>
        <ul>
            <li>
                <p>Assurez-vous de choisir un <span class="souligne">mot de passe fort</span>, composé d'au moins <span class="souligne">8 caractères</span>, de <span class="souligne">lettres majuscules</span>, de <span class="souligne">lettres minuscules</span>, de <span class="souligne">chiffres</span> et de <span class="souligne">caractères spéciaux</span>.</p>
            </li>
            <li>
                <p>N'utilisez pas le même mot de passe sur plusieurs sites Web pour renforcer la sécurité de votre compte.</p>
            </li>
            <li>
                <p>Si vous avez des questions ou rencontrez des problèmes lors de la réinitialisation de votre mot de passe, n'hésitez pas à nous contacter via notre <a href="https://laure-web.fr/index.php?route=contactMail">Page de Contact</a>.</p>
            </li>
        </ul>
    </div>
</section>