<h2>recettes</h2>

<table class="dashboard-table">
    <thead>
        <tr>
            <th>id</th>
            <th>recette</th>
            <th>produit</th>
            <th>difficulté</th>
            <th colspan="3">actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($recipes as $recipe) : ?>
            <tr>
                <td><?= htmlspecialchars($recipe["id"]); ?></td>
                <td><?= htmlspecialchars($recipe["name"]); ?></td>
                <td><?= htmlspecialchars($recipe["product_id"]); ?></td>
                <td><?= htmlspecialchars($recipe["difficulty"]); ?></td>
                <td>
                    <a href="index.php?route=displayUpdateRecipesForm&id=<?= htmlspecialchars($recipe['id']); ?>" data-text="Modifier la recette" class="aide left">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                </td>
                <td>
                    <a href="index.php?route=recipeDetail&id=<?= htmlspecialchars($recipe['id']); ?>" data-text="Voir la recette" class="aide left">
                        <i class="fa-solid fa-arrow-up-right-from-square"></i>
                    </a>
                </td>
                <td>
                    <a href="" data-text="Supprimer la recette" class="aide left">
                        <i class="fa-solid fa-trash-can"></i>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<hr>

<div class="buttons">
    <a href="index.php?route=displayCreateRecipesForm" class="btn">créer une recette</a>
</div>