<section class="content">
    <h1><?= htmlspecialchars($recipe["name"]) ?></h1>
    <figure class="">
        <!-- <a href="{{route('shopping.show', $product->id)}}"> -->
        <!-- @if ($product->image)
    <img src="/images/{{$product->img}}" alt="">
    @else -->
        <img src="public/img/Hades.jpg" alt="">
        <!-- @endif -->
        <figcaption>
            <p>ingrédient: <?= htmlspecialchars($product['name']) ?></p>
            <p>difficulté: <?= htmlspecialchars($recipe["difficulty"]) ?></p>
            <p>temps: <?= htmlspecialchars($recipe["time"]) ?></p>
            <p>temperature: <?= htmlspecialchars($recipe["thermostat"]) ?></p>
            <p>portions: <?= htmlspecialchars($recipe["portions"]) ?></p>
            <p>recette: <?= htmlspecialchars($recipe["recipe"]) ?></p>

            noter la recette :
            <form method="post" action="index.php?route=rateRecipes&id=<?= htmlspecialchars($recipe['id']) ?>">
                <div class="star-rating">
                    <input name="stars" id="star-a_<?= htmlspecialchars($recipe['id']) ?>" type="radio" value="5" 
                        <?php if ($recipe["note"] == 5) : echo ('checked="true"'); endif; ?>>
                    <label for="star-a_<?= htmlspecialchars($recipe['id']) ?>"></label>

                    <input name="stars" id="star-b_<?= htmlspecialchars($recipe['id']) ?>" type="radio" value="4" 
                        <?php if ($recipe["note"] == 4) : echo ('checked="true"'); endif; ?>>
                    <label for="star-b_<?= htmlspecialchars($recipe['id']) ?>"></label>

                    <input name="stars" id="star-c_<?= htmlspecialchars($recipe['id']) ?>" type="radio" value="3"  
                        <?php if ($recipe["note"] == 3) : echo ('checked="true"'); endif; ?>>
                    <label for="star-c_<?= htmlspecialchars($recipe['id']) ?>"></label>

                    <input name="stars" id="star-d_<?= htmlspecialchars($recipe['id']) ?>" type="radio" value="2"  
                        <?php if ($recipe["note"] == 2) : echo ('checked="true"'); endif; ?>>
                    <label for="star-d_<?= htmlspecialchars($recipe['id']) ?>"></label>

                    <input name="stars" id="star-e_<?= htmlspecialchars($recipe['id']) ?>" type="radio" value="1"  
                        <?php if ($recipe["note"] == 1) : echo ('checked="true"'); endif; ?>>
                    <label for="star-e_<?= htmlspecialchars($recipe['id']) ?>"></label>
                </div>

                <button type="submit" class="btn">noter</button>
            </form>
        </figcaption>
        <!-- </a> -->
    </figure>
</section>