<h2><?= $recipe["name"] ?></h2>
<figure class="">
    <!-- <a href="{{route('shopping.show', $product->id)}}"> -->
    <!-- @if ($product->image)
    <img src="/images/{{$product->img}}" alt="">
    @else -->
    <img src="public/img/Hades.jpg" alt="">
    <!-- @endif -->
    <figcaption>
        <p><?= $recipe["product_id"] ?></p>
        <p><?= $recipe["difficulty"] ?></p>
        <p><?= $recipe["time"] ?></p>
        <p><?= $recipe["thermostat"] ?></p>
        <p><?= $recipe["portions"] ?></p>
        <p><?= $recipe["recipe"] ?></p>
    </figcaption>
    <!-- </a> -->
</figure>