<section class="content">
    <?php if (isset($recipe['id'])) : ?>

        <h3>modifier une recette</h3>

        <form action="index.php?route=updateRecipeForm" method="post">
            <div>
                <label for="name">nom</label>
                <input type="text" name="name" id="name" required value="<?= $recipe['name'] ?>">
            </div>
            <div>
                <label for=" product_id">inrédient principal</label>
                <select name="product_id" id="product_id">
                    <option value="<?= $product['id'] ?>"><?= $recipe['productName'] ?></option>
                    <?php foreach ($products as $product) : ?>
                        <option value="<?= $product['id'] ?>"><?= $product['name'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <label for="difficulty">difficulté</label>
                <input type="range" name="difficulty" id="difficulty" min="1" max="5" value="<?= $recipe['difficulty'] ?>">
            </div>
            <div>
                <label for="time">temps</label>
                <input type="time" name="time" id="time" value="<?= $recipe['time'] ?>">
            </div>
            <div>
                <label for="recipe">recette</label>
                <textarea name="recipe" id="recipe" cols="30" rows="10" required><?= $recipe['recipe'] ?></textarea>
            </div>
            <div>
                <label for="thermostat">thermostat</label>
                <input type="number" name="thermostat" id="thermostat" value="<?= $recipe['thermostat'] ?>">
            </div>
            <div>
                <label for="portions">nombre de personnes</label>
                <input type="number" name="portions" id="portions" value="<?= $recipe['portions'] ?>">
            </div>
            <div>
                <label for="img">image</label>
                <input type="file" name="img" id="img">
            </div>
            <button type="submit" class="btn" value="">envoyer</button>
        </form>

    <?php else : ?>

        <h3>créer une recette</h3>

        <form action="index.php?route=submitRecipeForm" method="post">
            <div>
                <label for="name">nom</label>
                <input type="text" name="name" id="name" required>
            </div>
            <div>
                <label for="product_id">inrédient principal</label>
                <select name="product_id" id="product_id">
                    <option value="">---</option>
                    <?php foreach ($products as $product) : ?>
                        <option value="<?= $product['id'] ?>"><?= $product['name'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <label for="difficulty">difficulté</label>
                <input type="range" name="difficulty" id="difficulty" min="1" max="5">
            </div>
            <div>
                <label for="time">temps</label>
                <input type="time" name="time" id="time">
            </div>
            <div>
                <label for="recipe">recette</label>
                <textarea name="recipe" id="recipe" cols="30" rows="10" required></textarea>
            </div>
            <div>
                <label for="thermostat">thermostat</label>
                <input type="number" name="thermostat" id="thermostat">
            </div>
            <div>
                <label for="portions">nombre de personnes</label>
                <input type="number" name="portions" id="portions">
            </div>
            <div>
                <label for="img">image</label>
                <input type="file" name="img" id="img">
            </div>

            <div class="buttons">
                <button type="submit" class="btn" value="submit">envoyer</button>
                <button href="index.php?route=admin" class="btn">annuler</button>
            </div>
        </form>

    <?php endif ?>
</section>