<section class="content">
    <?php if (isset($recipe['id'])) : ?>

        <h2>modifier une recette</h2>

        <form action="index.php?route=updateRecipeForm" method="post">
            <div>
                <label for="name">nom</label>
                <input type="text" name="name" id="name" required value="<?= htmlspecialchars($recipe['name']) ?>">
            </div>
            <div>
                <label for=" product_id">inrédient principal</label>
                <select name="product_id" id="product_id">
                    <option value="<?= htmlspecialchars($product['id']) ?>"><?= htmlspecialchars($recipe['productName']) ?></option>
                    <?php foreach ($products as $product) : ?>
                        <option value="<?= htmlspecialchars($product['id']) ?>"><?= htmlspecialchars($product['name']) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <label for="difficulty">difficulté</label>
                <select name="difficulty" id="difficulty">
                    <option value="1" >facile</option>
                    <option value="2">moyen</option>
                    <option value="3">difficile</option>
                </select>
                <input type="range" name="difficulty" id="difficulty" min="1" max="3" value="<?= htmlspecialchars($recipe['difficulty']) ?>">
            </div>
            <div>
                <label for="time">temps</label>
                <input type="time" name="time" id="time" value="<?= htmlspecialchars($recipe['time']) ?>">
            </div>
            <div>
                <label for="recipe">recette</label>
                <textarea name="recipe" id="recipe" cols="30" rows="10" required><?= htmlspecialchars($recipe['recipe']) ?></textarea>
            </div>
            <div>
                <label for="thermostat">thermostat</label>
                <input type="number" name="thermostat" id="thermostat" value="<?= htmlspecialchars($recipe['thermostat']) ?>">
            </div>
            <div>
                <label for="portions">nombre de personnes</label>
                <input type="number" name="portions" id="portions" value="<?= htmlspecialchars($recipe['portions']) ?>">
            </div>
            <div>
                <label for="img">image</label>
                <input type="file" name="img" id="img">
            </div>
            <button type="submit" class="btn" value="">envoyer</button>
        </form>

    <?php else : ?>

        <h2>créer une recette</h2>

        <form action="index.php?route=submitRecipeForm" method="post">
            <div>
                <label for="name">nom</label>
                <input type="text" name="name" id="name" required>
            </div>
            <div>
                <label for="product_id">inrédient principal</label>
                <select name="product_id" id="product_id">
                    <option value="">---</option>
                    <?php foreach ($products as $product) : ?>
                        <option value="<?= htmlspecialchars($product['id']) ?>"><?= htmlspecialchars($product['name']) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <label for="difficulty">difficulté</label>
                <select name="difficulty" id="difficulty">
                    <option value=" 1">facile</option>
                    <option value="2">moyen</option>
                    <option value="3">difficile</option>
                </select>
            </div>
            <div>
                <label for="time">temps</label>
                <input type="time" name="time" id="time">
            </div>
            <div>
                <label for="recipe">recette</label>
                <textarea name="recipe" id="recipe" cols="30" rows="10" required></textarea>
            </div>
            <div>
                <label for="thermostat">thermostat</label>
                <input type="number" name="thermostat" id="thermostat">
            </div>
            <div>
                <label for="portions">nombre de personnes</label>
                <input type="number" name="portions" id="portions">
            </div>
            <div>
                <label for="img">image</label>
                <input type="file" name="img" id="img">
            </div>

            <div class="buttons">
                <button type="submit" class="btn" value="submit">envoyer</button>
                <button href="index.php?route=admin" class="btn">annuler</button>
            </div>
        </form>

    <?php endif; ?>
</section>