<section class="content">
    <h2>Toutes les recettes</h2>
    <article class="recipe-index">
        <?php foreach ($recipes as $recipe) : ?>
            <figure class="recipe-tuile" onclick="location.href='index.php?route=recipeDetail&id=<?= $recipe['id'] ?>'">

                <?php if (isset($recipe["img"])) : ?>
                    <!-- <img src="/images/{{$product->img}}" alt=""> -->
                <?php else : ?>
                    <img src="public/img/Hades.jpg" alt="">
                <?php endif; ?>

                <figcaption>
                    <h5><?= $recipe["name"] ?></h5>
                    <div class="infos">
                        <p><?= $recipe["time"] ?></p>
                        <input 
                        class="rating"
                        type="range" 
                        min="1" 
                        max="5" 
                        value="<?php $recipe["difficulty"] ?>" 
                        disabled>
                    </div>
                </figcaption>
            </figure>
        <?php endforeach; ?>
    </article>
</section>