<h2>news</h2>

<!-- <ul>
                <li>pagination</li>
                <li>confirm avant suppression</li>
                <li>rester sur le bon onglet</li>
            </ul> -->

<!-- display -->
<h3>Toutes les actus</h3>
<table class="dashboard-table">
    <thead>
        <tr>
            <th>id</th>
            <th>titre</th>
            <th>créé le</th>
            <th>modifié le</th>
            <th colspan="3">actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($news as $actu) : ?>
            <tr>
                <td><?= htmlspecialchars($actu["id"]); ?></td>
                <td><?= htmlspecialchars($actu["title"]); ?></td>
                <td><?= htmlspecialchars($actu["created_at"]); ?></td>
                <td><?= htmlspecialchars($actu["updated_at"]); ?></td>
                <td>
                    <a href="index.php?route=displayUpdateNewsForm&id=<?= htmlspecialchars($actu['id']); ?>" data-text="Modifier l'article" class="aide left">
                        <i class="fa-solid fa-pen-to-square"></i>
                    </a>
                </td>
                <td>
                    <a href="index.php?route=newsDetail&id=<?= htmlspecialchars($actu['id']); ?>" data-text="Voir l'article" class="aide left">
                        <i class="fa-solid fa-arrow-up-right-from-square"></i>
                    </a>
                </td>
                <td>
                    <a href="index.php?route=deleteNews&id=<?= htmlspecialchars($actu['id']); ?>" data-text="Supprimer l'article" class="aide left">
                        <i class="fa-solid fa-trash-can"></i>
                    </a>
                </td>
                <!-- onclick="confirmDelete()" -->
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<hr>

<div class="buttons">
    <a href="index.php?route=displayCreateNewsForm" class="btn">créer une nouvelle actu</a>
</div>