<section class="content">
    <article class="news-detail">
        <h1><?= $actu["title"] ?></h1>

        <ul>
            <li>ne peut pas utiliser "htmlspecialchars" sur $actu["message"]</li>
        </ul>
        
        <figure class="article">
            <?php if (isset($actu["img"])): ?>
                <!-- <img src="/images/{{$product->img}}" alt=""> -->
            <?php else: ?>
                <img src="public/img/Hades.jpg" alt="">
            <?php endif; ?>

            <figcaption>
                <?= $actu["message"] ?>
            </figcaption>
        </figure>


        <div class="date">
            <?php if ($actu["created_at"] != $actu["updated_at"]): ?>
                <p class="timestamp">modifié le : <?= htmlspecialchars($actu["updated_at"]) ?></p>
            <?php else: ?>
                <p class="timestamp">créé le : <?= htmlspecialchars($actu["created_at"]) ?></p>
            <?php endif; ?>
        </div>
    </article>
</section>