<h2><?= $actu["title"] ?></h2>
<figure class="">
    <!-- <a href="{{route('shopping.show', $product->id)}}"> -->
    <!-- @if ($product->image)
    <img src="/images/{{$product->img}}" alt="">
    @else -->
    <img src="public/img/Hades.jpg" alt="">
    <!-- @endif -->
    <figcaption>
        <p><?= $actu["message"] ?></p>
        <p><?= $actu["created_at"] ?></p>
        <p><?= $actu["updated_at"] ?></p>
    </figcaption>
    <!-- </a> -->
</figure>