<?php if (isset($actu['id'])) : ?>

    <h3>modifier une actu</h3>
    <form action="index.php?route=updateNews&id=<?= $actu['id'] ?>" method="post">
        <div>
            <label for="title">titre</label>
            <input type="text" name="title" id="title" required value="<?= $actu["title"] ?>">
        </div>
        <div>
            <label for="message">article</label>
            <textarea name="message" id="editor" cols="30" rows="10"><?= $actu["message"] ?></textarea>
        </div>
        <button type="submit" class="btn" value="submit">envoyer</button>
    </form>
    </section>

<?php else : ?>

    <h3>créer une actu</h3>
    <form action="index.php?route=submitNews" method="post">
        <div>
            <label for="title">titre</label>
            <input type="text" name="title" id="title" required>
        </div>
        <div>
            <label for="message">article</label>
            <textarea name="message" id="editor" cols="30" rows="10"></textarea>
        </div>
        <button type="submit" class="btn" value="submit">envoyer</button>
    </form>

<?php endif ?>