<section class="content dashboard-form">
    <?php if (isset($actu['id'])): ?>

        <h2>modifier une actu</h2>
        <form action="index.php?route=updateNews&id=<?= htmlspecialchars($actu['id']); ?>" method="post">
            <div>
                <label for="title">titre</label>
                <input type="text" name="title" id="title" required value="<?= htmlspecialchars($actu["title"]); ?>">
            </div>
            <div>
                <label for="message">article</label>
                <textarea name="message" id="editor" cols="30" rows="30"><?= $actu["message"] ?></textarea>
            </div>
            <div class="buttons">
                <button type="submit" class="btn" value="submit">envoyer</button>
                <button href="index.php?route=admin" class="btn">annuler</button>
            </div>
        </form>

    <?php else: ?>

        <h2>créer une actu</h2>
        <form action="index.php?route=submitNews" method="post">
            <div>
                <label for="title">titre</label>
                <input type="text" name="title" id="title" required>
            </div>
            <div>
                <label for="message">article</label>
                <textarea name="message" id="editor" cols="30" rows="30"></textarea>
            </div>
            <div class="buttons">
                <button type=" submit" class="btn" value="submit">envoyer</button>
                <a href="index.php?route=admin" class="btn">annuler</a>
            </div>
        </form>

    <?php endif; ?>
</section>