<div class="title">
    <h2>Les dernières news</h2>
    <a href="index.php?route=news" class="btn">afficher plus</a>
</div>

<div>
    <article class="news-home">
        <p>
            Je suis Arnaud, passionné de cuisine et de bien-manger. <br />
            J’ai travaillé pendant 20 ans en industrie (embouteillage et traitement de l’eau).<br />
            J’ai décidé de créer cette entreprise pour que mon travail soit en accord avec mes valeurs personnelles.<br />
            “Les pâtes du chat”, c’est une entreprise de fabrication de pâtes fraîches, de raviolis, de gnocchis.<br />
            Un des objectifs est de proposer des produits frais, sains, gourmands, de saison, dont les ingrédients sont très majoritairement issus de nos terres régionales !
        </p>
        <img src="./public/img/arnaud.png" alt="" srcset="">
    </article>

    <?php foreach ($news as $actu) : ?>
        <a href="index.php?route=newsDetail&id=<?= htmlspecialchars($actu['id']); ?>">
            <article class="news-home">
                <p><?= htmlspecialchars($actu["title"]); ?></p>
            </article>
        </a>
    <?php endforeach; ?>
</div>