<section class="content">
    <h2>Toutes les news</h2>
    <h4>trier les news</h4>
    <div class="news-index">
        <?php foreach ($news as $actu) : ?>
            <figure class="news-short">
                <!-- <a href="{{route('shopping.show', $product->id)}}"> -->
                <!-- @if ($product->image)
                            <img src="/images/{{$product->img}}" alt="">
                            @else -->
                <img src="public/img/Hades.jpg" alt="">
                <!-- @endif -->
                <figcaption>
                    <h5><?= $actu["title"] ?></h5>
                    <div class="short"><?= $actu["message"] ?></div>
                    <?php if ($actu["created_at"] != $actu["updated_at"]) : ?>
                        <p class="timestamp">modifié le : <?= $actu["updated_at"] ?></p>
                    <?php else : ?>
                        <p class="timestamp">créé le : <?= $actu["created_at"] ?></p>
                    <?php endif; ?>
                    <a href=" index.php?route=newsDetail&id=<?= $actu['id'] ?>" class="more">
                        <p>Lire la suite</p>
                        <p>Suite</p>
                    </a>
                </figcaption>
                <!-- </a> -->
            </figure>
        <?php endforeach; ?>
        </article>
    </div>
</section>