<section class="content">
    <h2>Toutes les news</h2>
    <div class="">
        <?php foreach ($news as $actu) : ?>
            <figure class="shop-tuile">
                <!-- <a href="{{route('shopping.show', $product->id)}}"> -->
                <!-- @if ($product->image)
                            <img src="/images/{{$product->img}}" alt="">
                            @else -->
                <img src="public/img/Hades.jpg" alt="">
                <!-- @endif -->
                <figcaption>
                    <h5><?= $actu["titre"] ?></h5>
                    <a href="index.php?route=newsDetail&id=<?= $actu['id'] ?>" class="btn">Voir plus</a>
                </figcaption>
                <!-- </a> -->
            </figure>
        <?php endforeach; ?>
        </article>
    </div>
</section>