<section class="content">
    <h1>Quoi de neuf chez le chat ?</h1>

    <!-- <ul>
        <li>format de date</li>
        <li>vidéo ne s'affichent pas</li>
    </ul> -->

    <div class="news-index">

        <a href="">
            <article class="news-short">
                <img src="./public/img/arnaud.png" alt="Arnaud, artisan pastier">
                <section>
                    <h2>Présentation</h2>
                    <p class="short">
                        Je suis Arnaud, passionné de cuisine et de bien-manger. <br />
                        J’ai travaillé pendant 20 ans en industrie (embouteillage et traitement de l’eau).<br />
                        J’ai décidé de créer cette entreprise pour que mon travail soit en accord avec mes valeurs personnelles.<br />
                        “Les pâtes du chat”, c’est une entreprise de fabrication de pâtes fraîches, de raviolis, de gnocchis.<br />
                        Un des objectifs est de proposer des produits frais, sains, gourmands, de saison, dont les ingrédients sont très majoritairement issus de nos terres régionales !
                    </p>
                    <a href="" class="more">
                        <div>
                            <p>Lire la suite</p>
                            <p><i class="fa-solid fa-arrow-right"></i></p>
                        </div>
                    </a>
                </section>
            </article>
        </a>
        <?php foreach ($news as $actu) : ?>
            <a href="index.php?route=newsDetail&id=<?= htmlspecialchars($actu['id']); ?>">
                <article class="news-short">
                    <?php if (isset($product["img"])) : ?>
                        <!-- <img src="/images/{{$product->img}}" alt=""> -->
                    <?php else : ?>
                        <img src="public/img/Hades.jpg" alt="">
                    <?php endif; ?>
                    <section>
                        <h2><?= htmlspecialchars($actu["title"]); ?></h2>
                        <div class="short"><?= $actu["message"] ?></div>
                        <?php if ($actu["created_at"] != $actu["updated_at"]) : ?>
                            <p class="timestamp">modifié le : <?= $actu["updated_at"] ?></p>
                        <?php else : ?>
                            <p class="timestamp">créé le : <?= htmlspecialchars($actu["created_at"]); ?></p>
                        <?php endif; ?>
                        <a href=" index.php?route=newsDetail&id=<?= htmlspecialchars($actu['id']); ?>" class="more">
                            <div>
                                <p>Lire la suite</p>
                                <p><i class="fa-solid fa-arrow-right"></i></p>
                            </div>
                        </a>
                    </section>
                </article>
            </a>
        <?php endforeach; ?>
    </div>
</section>